---
- name: Play For Installing Nginx Server
  hosts: webservers
  become: Yes
  become_user: root
  tasks:
  - name: Perform Apt Update
    shell: apt update
    tags:
    - update

  - name: Install Nginx
    shell: apt install -y nginx
    tags:
    - install

  - name: Start Nginx Service
    shell: service nginx start
    tags:
    - services
  tags:
    - nginx

- name: Play For Creating adminuser
  hosts: allservers
  become: Yes
  become_user: root
  tasks:
  - name: User Creation
    user:
     name: "vikram"
     state: "present"
     shell: "/bin/bash"
  tags:
  - users