---
- name: Install Nginx Using Ansible Role
  hosts: private
  become: yes
  become_user: root
  roles:
  - { role: geerlingguy.mysql }
  tasks:
  - name: create a new database
    mysql_db: >
      name=myflixdb
      state=present
      login_user=root
  - name: Add sample data to database
    copy: src=dump.sql dest=/tmp/dump.sql
  - name: insert sample data into database
    mysql_db: name=myflixdb state=import target=/tmp/dump.sql